In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print 
the data types of both the variables.

In [ ]:
ANS- Yes, there is a difference in the data type of list_ and array_list.

list_ is a Python list containing string elements, while array_list is a NumPy array that contains elements of the data type numpy.str_, 
which is similar to the Python string data type but optimized for use in NumPy arrays.

Here is the code to print the data types of both variables:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print('Data type of list_:', type(list_))
print('Data type of array_list:', type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for i in list_:
    print('Data type of element in list_:', type(i))

# Print data type of each element in array_list
for i in array_list:
    print('Data type of element in array_list:', type(i))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


In [ ]:
3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print 
the data types of each and every element present in both the variables, list_ and arra_list.

Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
ANS- Yes, there will be a difference in the data type of the elements present in list_ and array_list when array_list is created as follows:
    
    array_list = np.array(object=list_, dtype=int)
    
    
In this case, the dtype parameter is set to int, which means that the elements in list_ will be converted to integers 
when the array_list is created.

Here is the code to print the data type of each element in both list_ and array_list:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for i in list_:
    print('Data type of element in list_:', type(i))

# Print data type of each element in array_list
for i in array_list:
    print('Data type of element in array_list:', type(i))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


In [ ]:
As we can see, the data type of each element in list_ is str, while the data type of each element in array_list is numpy.int64.

Regarding the code snippet you provided for num_list and num_array, it creates a 2-dimensional NumPy array num_array using the 
np.array function, which takes a nested list num_list as an argument. The resulting array num_array has dimensions 2x3, and contains 
the same values as num_list.

In [ ]:
4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Find shape of num_array
print('Shape of num_array:', num_array.shape)

# Find size of num_array
print('Size of num_array:', num_array.size)


'''As we can see, the shape of num_array is (2, 3), which means it has 2 rows and 3 columns, and the size of num_array is 6, 
which means it contains a total of 6 elements.'''

Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
import numpy as np

# Create 3x3 NumPy array containing zeros
zero_array = np.zeros((3, 3))

# Print zero_array
print(zero_array)

'''As we can see, zero_array is a 3x3 NumPy array containing only zeros, created using the np.zeros() function. 
The function takes a tuple (3, 3) as an argument to specify the shape of the array.'''

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
import numpy as np

# Create 5x5 identity matrix
identity_matrix = np.identity(5)

# Print identity_matrix
print(identity_matrix)

'''As we can see, identity_matrix is a 5x5 matrix containing 1 diagonally and 0 elsewhere, created using the np.identity() function. 
The function takes an integer argument to specify the size of the square identity matrix.'''

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
